### ISSUE TITLE
fzf completion is incorrect when I set breakpoint at runtime

### ISSUE THREAD

**Issue by YalandHong** [lebr0nli/GEP#14]
Hello,

First, thanks for making this simple yet awesome tool!  :D

**Here's the bug description:**

When I set breakpoint after I `run` the program, the fzf tab auto-completion for symbol name encounters weird behavior.

For example, if I type `B` then press `<tab>`, the first character of each symbol name is overwritten as `B`.

See the following screenshot. The function name `foo::B::func()` is displayed as `Boo::B::func()`. Thus, if I press enter for completion, it will fill the name as `Boo::B::func()`.

It seems that GEP has some problem with searching non-prefix string.

![image](https://github.com/lebr0nli/GEP/assets/52960068/ec3366e2-479a-4c20-88d6-aa66a93b786b)

**Here's the source.cpp:**
```cpp
#include <iostream>
using namespace std;

namespace foo {
class B {
  public:
    void func()
    {
        cout << "B:func" << endl;
    }
};
}
int main()
{
    foo::B b;
    b.func();
    return 0;
}
```

**Here's my system info:**
```
Ubuntu 20.04 (WSL 1) with all packages installed from APT
g++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
GNU gdb (Ubuntu 9.2-0ubuntu1~20.04.1) 9.2
Python 3.8.10
```

Please note that the above example is very simple. I don't if this problem occurs BEFORE I `run` the program.

**Comment by lebr0nli** [comment]
Hi, thanks for the bug report!

I tried `print B<tab>` with the `source.cpp` you provided, then I got:
<img width="1170" src="https://github.com/lebr0nli/GEP/assets/61896187/d15d8e4b-ff41-4e8d-b7c0-a46cb8ab22b3">

The result is buggy because these function names start with `b` instead of `B`.

But somehow I can't reproduce the same bug you found. (showing `Boo::B::func()`)
What's the prefix before you press the tab? Did you also do something like `print B<tab>`?

**Comment by YalandHong** [comment]
I typed `b B<tab>`.

And, obviously, you triggered another bug about fuzzy search ignoring case.  😂

**Comment by lebr0nli** [comment]
> I typed `b B<tab>`.

I just successfully reproduced the bug here.
I'll try to fix it.
Thanks for the detailed bug report 🙏

**Comment by lebr0nli** [comment]
Hi @YalandHong, I made a patch for this issue in #15.
The bugs seem fix for me with it (it still have some room for improvement tho, but I don't have good idea currently :p)
Can you help me to test if that patch also works for you? Thanks!

**Comment by YalandHong** [comment]
I confirmed. It works fine for me.

Thanks for the patch!

**Comment by lebr0nli** [comment]
Great, thanks for helping test it!
