### ISSUE TITLE
Problem with completion popup text

### ISSUE THREAD

**Issue by fikovnik** [lebr0nli/GEP#2]
I was trying out this plugin (really cool btw) and I think there is a problem with the completion:

For example:

![GEP](https://user-images.githubusercontent.com/374674/170007727-af816930-9e53-4f10-a36f-45cb30e46f53.png)

The `rho))` prefix is off.

**Comment by lebr0nli** [comment]
Hi, thanks for reporting the bug!

I think I know where's going wrong after some testing, I'll try to fix it!

By the way, is it possible to provide the steps to reproduce it or the binary you debugging on?

Thanks!

**Comment by fikovnik** [comment]
The binary is the [R interpreter](https://cran.r-project.org/), once installed / compiled with debugging symbols, you can run it with debugger attached:

```
R -d gdb
```

put a breakpoint somwehere, e.g. `Rf_eval` function and run the program:

```
b Rf_eval
r
```

then you can try the following:
![GEP2](https://user-images.githubusercontent.com/374674/170034032-aa5e1bf2-5fe1-4583-82ba-340fd6810549.png)

the prefix `R_inspect` should not be part of the completion.

Or trigger the suffix:

![GEP3](https://user-images.githubusercontent.com/374674/170034036-a2db89da-f81b-4e4b-9e79-5cabcda8d078.png)

**Comment by lebr0nli** [comment]
After some testing, I think there are two problems:

1. Autocompletion should base on the text before the cursor, not based on the full text in the input buffer

2. `\W+` should be used to split the display text in the popup instead of using spaces, which means:

> then you can try the following: ![GEP2](https://user-images.githubusercontent.com/374674/170034032-aa5e1bf2-5fe1-4583-82ba-340fd6810549.png)
 
The text in the popup should be changed to:

```text
Rf_lang1
Rf_lang2
Rf_lang3
Rf_lang4
Rf_lang5
Rf_lang6
Rf_lastElt
```

**Comment by lebr0nli** [comment]
Hi @fikovnik , thanks for the details you provided, these details are really helpful!

For some reason, I can't build the R interpreter with debug info successfully now. Can you help me to check if the bug is still there after this update? Is the new logic of autocompletion make sense?

Thanks!

**Comment by fikovnik** [comment]
Perfect! Thanks for the fix!
