### ISSUE TITLE
Error when starting gdb

### ISSUE THREAD

**Issue by diohabara** [lebr0nli/GEP#3]
When I installed as instructed in README,

```bash
$ bash -c "$(curl -fsSL https://raw.githubusercontent.com/lebr0nli/GEP/main/install.sh)"
```

I've got this error when starting GDB.

```
File "~/GEP/.gdbinit-gep.py", line 77
    fzf_cmd = [f"awk '!seen[$0]++' {shlex.quote(HISTORY_FILENAME)}"]
                                                                  ^
SyntaxError: invalid syntax
```

**Comment by lebr0nli** [comment]
Hi, can you provide the Python version of your GDB? (You can `pi sys.version` inside GDB)

And it is probably because f-string is a Python 3.6 syntax, and you are using maybe Python 3.5 or something.

**Comment by diohabara** [comment]
@lebr0nli
You're right. Then version of Python(`usr/bin/python`) was `3.5.2`.
Is it possible to use `python3` rather than `python` to avoid this error? This is because `python` command is often for prebuilt one and what I install is `python3`.

**Comment by lebr0nli** [comment]
> Is it possible to use `python3` rather than `python` to avoid this error? This is because `python` command is often for prebuilt one and what I install is `python3`.

@diohabara, I'm afraid we can't. The only solution is compiling the GDB manually with `--with-python=/the/path/to/your/python3` IIRC.

But actually, we can fix this problem by using %-formatting for better compatibility for the lower version.

But yeah, Python 3.5 is really old, should we change the code just for that?

I didn't have this kind of experience, so feel free to share your ideas with me :)

**Comment by lebr0nli** [comment]
@diohabara 

Anyway, I use %-formatting eventually, so the issue should be fixed now.

Let me know if it doesn't work for you.

**Comment by qiuwei** [comment]
> @diohabara
> 
> Anyway, I use %-formatting eventually, so the issue should be fixed now.
> 
> Let me know if it doesn't work for you.

Seems there are bugs introduced.

https://github.com/lebr0nli/GEP/pull/4

**Comment by lebr0nli** [comment]
@qiuwei, I merged that PR now
Thanks for pointing it out!
